resolver: lts-6.35

allow-newer: true

packages:
- '.'

extra-deps:
- OpenGLRaw-1.5.0.1
- bitmap-0.0.2
- lambdacube-core-0.2.0
- lambdacube-edsl-0.2.0
- lambdacube-gl-0.2.2

flags:
  lafonten:
    test: true
